#A Linguagem de marcação YAML é facil de interpretar e ler
#Mas quando usada no GitHub Action precisa ser seguido pois a ferramenta precisa entender o que esta senod pedido para ela
#Git Hub Actions é o nome da extensão
#Workful é como a defiunição de passos que devem ocorrer em algum evento.
name: Test Application #definimos o nome da aplicação
on: push #definição de quando o evento deve acontecer.
jobs: #jobs sap tarefas particulartes que queremos executar dentro do workflow (temos o limite de ate 256) as atrefas sao executadas em paralelo
  test:
    runs-on: ubuntu-22.04 #runs-on: define em qual tipo de máquina aquelça tarefa precisa ser executada
#github action executa as atrefas que definimos dentro do container do docker peermitindo isolar o ambiente de execução
  #depois de delcarar a existência do job é necessario configurar algumas infromações para que ele execute.
    steps: #É como uma lista onde podemos definir quais sao os passos necessarios para completar o job.
        name: Checkout
        uses: actions/checkout@v5.0.0
#podemos rodar comando aqui como se estivessemos no shell
#agora que ja temos o codigo é necessário baixar e configurar o Python dentro do container com uma action ja existente, a actions/setup-python
        name: Set up Python
        uses: actions/setup-python@v5
        #usando parametros (dessa para versão)
        with:
          python-version: "3.13"